### PR TITLE
launcher: add distributed ssh launcher

### PR DESCRIPTION
**Pull request by ymjiang**

### CODE REVIEW

**Comment by ymjiang** [comment]
@bobzhuyb The script has been tested. Just take a look if need to add anything else.

**Comment by bobzhuyb** [comment]
How do you handle stdout and stderr? Can you redirect them to local files, or redirect them to remote files but have some ways to collect them?

**Comment by ymjiang** [comment]
It can collect stdout and stderr and show them on local terminal output.

**Comment by ymjiang** [comment]
@bobzhuyb stdout and stderr of each worker/server/scheduler have been redirected to local files under  `sshlog/`

**Pull request merged**
