### PR TITLE
common: fix the problem of different CPU tensor using the same name

### PR DESCRIPTION
**Pull request by bobzhuyb**
Trying to address https://github.com/bytedance/byteps/issues/247

### CODE REVIEW

**Comment by vycezhong** [comment]
@bobzhuyb  compile error

```sh
byteps/common/operations.cc: In function 'byteps::common::Status byteps::common::EnqueueTensor(byteps::common::BPSContext&, std::shared_ptr<byteps::common::Tensor>, std::shared_ptr<byteps::common::Tensor>, std::shared_ptr<byteps::common::ReadyEvent>, int, int, int, byteps::common::StatusCallback, std::shared_ptr<std::vector<byteps::common::QueueType> >)':
byteps/common/operations.cc:192:51: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
     cudaError_t err = cudaHostRegister(input->data(), input->size(), cudaHostRegisterMapped);
```

**Comment by vycezhong** [comment]
@bobzhuyb  

```sh
In file included from /usr/local/cuda/include/channel_descriptor.h:61:0,
                 from /usr/local/cuda/include/cuda_runtime.h:95,
                 from byteps/common/common.h:21,
                 from byteps/common/operations.h:20,
                 from byteps/common/operations.cc:16:
/usr/local/cuda/include/cuda_runtime_api.h:4727:39: note: candidate: cudaError_t cudaHostGetDevicePointer(void**, void*, unsigned int) <near match>
 extern __host__ cudaError_t CUDARTAPI cudaHostGetDevicePointer(void **pDevice, void *pHost, unsigned int flags);
                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/cuda_runtime_api.h:4727:39: note:   conversion of argument 2 would be ill-formed:
In file included from byteps/common/communicator.h:33:0,
                 from byteps/common/global.h:29,
                 from byteps/common/operations.cc:23:
byteps/common/operations.cc:195:71: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
     CUDA_CALL(cudaHostGetDevicePointer(&(context.gpu_ptr), input->data(), 0));
```

**Comment by bobzhuyb** [comment]
@vycezhong Sorry, didn't test compiling it.,

**Comment by vycezhong** [comment]
@bobzhuyb  Thank you! It works, but runs a bit slow. is it expected because tensors are re-registered every time?

**Comment by bobzhuyb** [comment]
> @bobzhuyb Thank you! It works, but runs a bit slow. is it expected because tensors are re-registered every time?

Is it slower than the first commit? In general, CPU tensor handling is much slower than GPU tensors..

**Comment by vycezhong** [comment]
no, there is no too much difference between two commits. i mean i feel it is slow because it took nearly 1 min on average to run 10 rounds, including starting servers and workers time.

**Comment by bobzhuyb** [comment]
@vycezhong Do you have a lot of CPU tensors to push/pull?

**Comment by vycezhong** [comment]
@bobzhuyb  no. just a tiny tensor. 

```py
import mxnet as mx
from mxnet import nd
from mxnet.test_utils import almost_equal
import numpy as np

import byteps.mxnet as bps

bps.init()
bps.byteps_declare_tensor("tmp")
for i in range(5):
  expected = nd.random.normal(shape=2)
  tmp = expected.copy()
  bps.byteps_push_pull(tmp, name="tmp", is_average=False)
  tmp /= bps.size()
  print(expected.asnumpy(), tmp.asnumpy(), flush=True)
  # assert almost_equal(tmp.asnumpy(), expected.asnumpy()), "failed at %d try" % i
```

**Comment by bobzhuyb** [comment]
Can you time the loop `for i in range(5):` ? In order to exclude server and worker startup time.  Would you use just 2 processes?

**Comment by vycezhong** [comment]
it only takes 0.12s for the loop with two workers in different machines. it looks reasonable.

**Pull request merged**
