### PR TITLE
tensorflow: reduce memory footprint during broadcast

### PR DESCRIPTION
**Pull request by bobzhuyb**
For training very large models like BERT-large

### CODE REVIEW

**Comment by bobzhuyb** [comment]
Still testing. Not fully finished yet.

**Comment by bobzhuyb** [comment]
Can you test Keras and TF?

**Comment by ymjiang** [comment]
@bobzhuyb I will test Keras.

**Comment by ymjiang** [comment]
Run keras and errors as follow:
```
[byteps/common/nccl_manager.cc:35] Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: an illegal memory access was encountered
byteps/example/keras/run_keras.sh: line 17: 19419 Aborted                 python $path/keras_imagenet_resnet50.py 
```

It can run normally if we fall back to `d6d5e4`.

**Pull request merged**
