### PR TITLE
docs: add bytescheduler reference in readme

### PR DESCRIPTION
**Pull request by yhpeng-git**

### CODE REVIEW

**Comment by ymjiang** [comment]
@bobzhuyb Shall we put it to somewhere else rather than in the limitations?

**Comment by bobzhuyb** [comment]
Maybe create a new section called "Publications", and put the texts there.

**Comment by yhpeng-git** [comment]
@ymjiang Changed accordingly.

**Comment by ymjiang** [comment]
@yhpeng-git How about make the format more formal? For example, below is copied from Horovod:

```
Publications
------------
1. Sergeev, A., Del Balso, M. (2017) *Meet Horovod: Uber’s Open Source Distributed Deep Learning Framework for TensorFlow*.
Retrieved from `https://eng.uber.com/horovod/ <https://eng.uber.com/horovod/>`_
```

So maybe we can make it like this:
```
"BytePS adopts similar ideas in ByteScheduler, ...... You can also find more details about ByteScheduler in the following paper:"

1. Author, author. (2019) Bytescheduler: A Generic Communication Scheduler for Distributed DNN Training Acceleration.
```

**Pull request merged**
