### PR TITLE
format: loosely enforce the code style

### PR DESCRIPTION
**Pull request by changlan**
- add contribution guidelines
- reformat all code with clang-format and autopep
- tweak type casts, conforming to google c++ style

@ymjiang: there should be no functional change, but would be nice to confirm it's working as before.

### CODE REVIEW

**Comment by byronyi** [comment]
Install clang-format, and do clang-format -i --style=google to all sources.

**Comment by ymjiang** [comment]
Cannot compile:

```
In file included from byteps/common/communicator.h:32:0,
                 from byteps/common/global.h:28,
                 from byteps/common/core_loops.cc:21:
byteps/common/core_loops.cc: In function 'void byteps::common::PostNcclCalls(std::shared_ptr<byteps::common::TensorTableEntry>, byteps::common::QueueType)':
byteps/common/core_loops.cc:182:35: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
           (const void *)p, (out_p + nccl_rank * num_elem_per_gpu * unit_len),
                                   ^
byteps/common/logging.h:64:23: note: in definition of macro 'NCCLCHECK'
     ncclResult_t r = (cmd);                                                 \
                       ^
In file included from byteps/common/common.h:21:0,
                 from byteps/common/core_loops.cc:20:
/usr/local/nccl/include/nccl.h:191:15: note: initializing argument 2 of 'ncclResult_t ncclReduceScatter(const void*, void*, size_t, ncclDataType_t, ncclRedOp_t, ncclComm_t, cudaStream_t)'
 ncclResult_t  ncclReduceScatter(const void* sendbuff, void* recvbuff,
               ^
In file included from byteps/common/communicator.h:32:0,
                 from byteps/common/global.h:28,
                 from byteps/common/core_loops.cc:21:
byteps/common/core_loops.cc:189:41: error: invalid conversion from 'const void*' to 'void*' [-fpermissive]
                            (out_p + len - left_elem * unit_len),
                                         ^
byteps/common/logging.h:64:23: note: in definition of macro 'NCCLCHECK'
     ncclResult_t r = (cmd);                                                 \
                       ^
In file included from byteps/common/common.h:21:0,
                 from byteps/common/core_loops.cc:20:
/usr/local/nccl/include/nccl.h:134:15: note: initializing argument 2 of 'ncclResult_t ncclReduce(const void*, void*, size_t, ncclDataType_t, ncclRedOp_t, int, ncclComm_t, cudaStream_t)'
 ncclResult_t  ncclReduce(const void* sendbuff, void* recvbuff, size_t count, ncclDataType_t datatype,
               ^
byteps/common/core_loops.cc: In function 'void byteps::common::CopyHost2Device(std::shared_ptr<byteps::common::TensorTableEntry>)':
byteps/common/core_loops.cc:522:58: error: reinterpret_cast from type 'const void*' to type 'char*' casts away qualifiers
   auto gpu_addr = reinterpret_cast<char *>(tensor->data()) + offset;
                                                          ^
error: None of TensorFlow, MXNet, PyTorch plugins were built. See errors above.
```

Besides, I think we should reach a consensus on the code style. @bobzhuyb any preference?

**Comment by changlan** [comment]
ps: It's not ready yet, pls wait until CI passes

**Comment by changlan** [comment]
@ymjiang Ready now. Please test.

**Pull request merged**
